// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqIh9rbrLk_ON5POLhSXh-D4aFKLP7YaA',
    appId: '1:777521057911:web:3b1874d7a865f0ef49f672',
    messagingSenderId: '777521057911',
    projectId: 'ajprojects-e3b2a',
    authDomain: 'ajprojects-e3b2a.firebaseapp.com',
    storageBucket: 'ajprojects-e3b2a.firebasestorage.app',
    measurementId: 'G-0PRGZ0R037',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL5AEz41Ch8WWu25kjDe6l0YWqEAzUBVc',
    appId: '1:777521057911:android:91b4cd70872d31d049f672',
    messagingSenderId: '777521057911',
    projectId: 'ajprojects-e3b2a',
    storageBucket: 'ajprojects-e3b2a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUFY3lQlVa2aWXxb4NQiEfFCpHWdvGm6A',
    appId: '1:777521057911:web:750e408eb6b4a12f49f672',
    messagingSenderId: '777521057911',
    projectId: 'ajprojects-e3b2a',
    authDomain: 'ajprojects-e3b2a.firebaseapp.com',
    storageBucket: 'ajprojects-e3b2a.firebasestorage.app',
    measurementId: 'G-HVGSNF949V',
  );
}
